apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aur4iig88-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aur4iig88-nodejs 
  name: aur4iig88-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: aur4iig88-nodejs 
